#The delay in ticks before the spell is cast
#Range: > 0
delay = 10
#The cost of casting this spell
#Range: > 0
cost = 0
#Cooldown for this prayer spell (2400 ticks = 2 minutes)
#Range: > 0
cooldown = 2400
#Base reputation gained from this prayer spell
#Range: > 0
base_reputation = 1
#Altar Power multiplier for reputation gained with this prayer spell
#Range: 0.0 ~ 1.7976931348623157E308
power_multiplier = 0.25

